name: lalo
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^1.13.1
  cloud_firestore: ^3.1.10
  firebase_auth: ^3.3.9
  google_sign_in: ^5.2.4
  firebase_analytics: ^9.1.2
  firebase_crashlytics: ^2.5.3
  google_fonts: ^2.3.1
  provider: ^6.0.2
  font_awesome_flutter: ^9.2.0
  flutterfire_ui: ^0.3.6
  settings_ui: ^2.0.2
  url_launcher: ^6.0.20
  cloud_functions: ^3.2.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
